@startuml DIAGRAMMECLASS

  class Users {
  - id : int
  - lastName : string
  - firstName : string
  - email : string
  - password : string
  - phone : string
  - createdAt : date
  - updatedAt : date


  + getId() : int
  + getLastName() : string
  + getFirstName() : string
  + getEmail() : string
  + getPassword() : string
  + getPhone() : string
  + getCreatedAt() : date
  + getUpdatedAt() : date

}


class Departments {
    - id : int
    - postalCode : int

    + getId() : int
    + getPostalCode() : int
}

class City {
    - id : int
    - name : string

    + getId() : int
    + getName() : string
}

Tenants"0..*" -- "1..*"Reservations: réserve
Owners"1..*" -- "1..1"Listings: possède
Listings"0..*" -- "1..*"Reservations: appartient
Listings"1..*" -- "0..*"Accommodations: appartient
Listings"1..1" -- City: appartient
Departments"1..*" -- "1..1"City: appartient
City"1..*" -- "1..1"Accommodations: appartient
    
@enduml